name: PR Checks

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: yarn install
        run: npm install -g yarn@v2

      - name: install dependencies
        run: yarn install
